"""Render the extension-owned UI pages that must track the runtime registry.

Two pages are generated rather than written by hand, because both restate facts
that live somewhere else and would otherwise drift:

* ``ui/pages/inventory-api.yaml`` lists every operation, its inputs and its
  results, straight from ``runtime/catalog.py``.
* ``ui/pages/changelog.yaml`` renders ``CHANGELOG.md``.

``tests/test_user_documentation.py`` fails if either shipped page differs from
what this module renders.
"""

from __future__ import annotations

import sys
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[2]
if str(BUNDLE_ROOT) not in sys.path:
    sys.path.insert(0, str(BUNDLE_ROOT))

from runtime.catalog import OPERATIONS  # noqa: E402
from runtime.documents import API_VERSION  # noqa: E402

CHANGELOG = BUNDLE_ROOT / "CHANGELOG.md"
CHANGELOG_PAGE = BUNDLE_ROOT / "ui" / "pages" / "changelog.yaml"
INVENTORY_PAGE = BUNDLE_ROOT / "ui" / "pages" / "inventory-api.yaml"

INDENT = "      "


def _block(lines: list[str]) -> str:
    """Indent a markdown body into a YAML block scalar.

    Trailing blank lines are dropped: the page template appends its own final
    newline, so a body ending in a blank separator would leave a blank line at
    end of file and `git diff --check` would flag every regeneration.
    """
    flattened: list[str] = []
    for line in lines:
        flattened.extend(str(line).split("\n"))
    while flattened and not flattened[-1].strip():
        flattened.pop()
    return "\n".join(f"{INDENT}{line}".rstrip() for line in flattened)


def _operation_lines() -> list[str]:
    lines: list[str] = [
        f"Every operation below is fixed in advance and typed against Shopify Admin GraphQL "
        f"`{API_VERSION}`. Nothing is discovered from your store, no operation accepts GraphQL "
        f"of its own, and there is no general-purpose request action.",
        "",
        "Each operation states its canonical `required_oauth_scopes` all-of requirement. New "
        "connections must grant the complete eight-scope set; an incomplete OAuth callback "
        "is rejected. `Test the connection` reports per-operation eligibility only to diagnose "
        "an older stale grant. Eligibility means the scopes permit the attempt — Shopify staff "
        "permissions, shop state and record state still decide the outcome.",
        "",
    ]
    for row in OPERATIONS:
        lines.append(f"### {row.display_name}")
        lines.append("")
        lines.append(row.description)
        lines.append("")
        lines.append(f"- Action id: `{row.operation_id}`")
        lines.append(f"- Kind: {row.kind}")
        lines.append(f"- Contacts Shopify: {'yes' if row.contacts_shopify else 'no'}")
        lines.append(f"- Available in workflows: {'yes' if row.workflow_visible else 'no'}")
        required = set(row.required_input_field_names)
        inputs = [
            f"`{name}`{'' if name in required else ' (optional)'}" for name in row.input_field_names
        ]
        lines.append(f"- Inputs: {', '.join(inputs) if inputs else 'none'}")
        lines.append(f"- Results: {', '.join(f'`{name}`' for name in row.result_fields)}")
        if not row.required_oauth_scopes:
            scope_text = "no business-resource scope"
        else:
            scope_text = ", ".join(f"`{name}`" for name in row.required_oauth_scopes)
        lines.append(f"- Scopes: {scope_text}")
        if row.effect_kind:
            lines.append(f"- External effect: `{row.effect_kind}`")
        lines.append("")
    return lines


def inventory_page() -> str:
    return (
        "\n".join(
            [
                "# Generated by tests/reference/build_ui_pages.py from runtime/catalog.py.",
                "# Do not edit by hand.",
                "page_id: inventory-api",
                "title: Inventory API",
                "description: Every Shopify operation this extension can run, and what each one needs.",
                "project_scoped: false",
                "components:",
                "  - component_id: inventory_api_operations",
                "    type: markdown",
                "    title: Operations",
                "    body: |",
                _block(_operation_lines()),
            ]
        )
        + "\n"
    )


def changelog_page() -> str:
    """The Changelog page renders CHANGELOG.md, so the two cannot disagree."""
    body = CHANGELOG.read_text(encoding="utf-8").strip()
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    return (
        "\n".join(
            [
                "# Generated by tests/reference/build_ui_pages.py from CHANGELOG.md.",
                "# Do not edit by hand.",
                "page_id: changelog",
                "title: Changelog",
                "description: What changed in each release of this extension.",
                "project_scoped: false",
                "components:",
                "  - component_id: changelog_entries",
                "    type: markdown",
                "    title: Release history",
                "    body: |",
                _block(lines),
            ]
        )
        + "\n"
    )


GENERATED_PAGES: dict[Path, object] = {
    INVENTORY_PAGE: inventory_page,
    CHANGELOG_PAGE: changelog_page,
}


def main() -> int:
    for path, render in GENERATED_PAGES.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(), encoding="utf-8")  # type: ignore[operator]
        print(f"wrote {path.relative_to(BUNDLE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "CHANGELOG_PAGE",
    "GENERATED_PAGES",
    "INVENTORY_PAGE",
    "changelog_page",
    "inventory_page",
]
