"""Render the extension-owned UI pages that must track the runtime registry.

Three pages are generated rather than written by hand, because each restates
facts that live somewhere else and would otherwise drift:

* ``ui/pages/inventory-api.yaml`` lists every operation, its inputs and its
  results, straight from ``runtime/catalog.py``.
* ``ui/pages/api-coverage.yaml`` states, per operation, how much of Shopify's
  official API it covers and what is deliberately not reachable and why, from
  the pinned schema slice and ``runtime/coverage.py``.
* ``ui/pages/changelog.yaml`` renders ``CHANGELOG.md``.

``tests/test_user_documentation.py`` fails if either shipped page differs from
what this module renders.
"""

from __future__ import annotations

import sys
from pathlib import Path

BUNDLE_ROOT = Path(__file__).resolve().parents[2]
if str(BUNDLE_ROOT) not in sys.path:
    sys.path.insert(0, str(BUNDLE_ROOT))
REFERENCE_ROOT = Path(__file__).resolve().parent
if str(REFERENCE_ROOT) not in sys.path:
    sys.path.insert(0, str(REFERENCE_ROOT))

import admin_schema  # noqa: E402
from graphql_selection import named_type, parse  # noqa: E402

from runtime import coverage  # noqa: E402
from runtime.catalog import OPERATIONS  # noqa: E402
from runtime.documents import API_VERSION  # noqa: E402

CHANGELOG = BUNDLE_ROOT / "CHANGELOG.md"
CHANGELOG_PAGE = BUNDLE_ROOT / "ui" / "pages" / "changelog.yaml"
INVENTORY_PAGE = BUNDLE_ROOT / "ui" / "pages" / "inventory-api.yaml"
COVERAGE_PAGE = BUNDLE_ROOT / "ui" / "pages" / "api-coverage.yaml"

INDENT = "      "


def _block(lines: list[str]) -> str:
    """Indent a markdown body into a YAML block scalar.

    Trailing blank lines are dropped: the page template appends its own final
    newline, so a body ending in a blank separator would leave a blank line at
    end of file and `git diff --check` would flag every regeneration.
    """
    flattened: list[str] = []
    for line in lines:
        flattened.extend(str(line).split("\n"))
    while flattened and not flattened[-1].strip():
        flattened.pop()
    return "\n".join(f"{INDENT}{line}".rstrip() for line in flattened)


def _operation_lines() -> list[str]:
    lines: list[str] = [
        f"Every operation below is fixed in advance and typed against Shopify Admin GraphQL "
        f"`{API_VERSION}`. Nothing is discovered from your store, no operation accepts GraphQL "
        f"of its own, and there is no general-purpose request action.",
        "",
        "Each operation states its canonical `required_oauth_scopes` all-of requirement. New "
        "connections must grant the complete eight-scope set; an incomplete OAuth callback "
        "is rejected. `Test the connection` reports per-operation eligibility only to diagnose "
        "an older stale grant. Eligibility means the scopes permit the attempt — Shopify staff "
        "permissions, shop state and record state still decide the outcome.",
        "",
    ]
    for row in OPERATIONS:
        lines.append(f"### {row.display_name}")
        lines.append("")
        lines.append(row.description)
        lines.append("")
        lines.append(f"- Action id: `{row.operation_id}`")
        lines.append(f"- Kind: {row.kind}")
        lines.append(f"- Contacts Shopify: {'yes' if row.contacts_shopify else 'no'}")
        lines.append(f"- Available in workflows: {'yes' if row.workflow_visible else 'no'}")
        if row.document:
            lines.append(f"- Shopify: `{parse(row.document).selections[0].name}`")
        required = set(row.required_input_field_names)
        inputs = [
            f"`{name}`{'' if name in required else ' (optional)'}" for name in row.input_field_names
        ]
        lines.append(f"- Inputs: {', '.join(inputs) if inputs else 'none'}")
        lines.append(f"- Results: {', '.join(f'`{name}`' for name in row.result_fields)}")
        if not row.required_oauth_scopes:
            scope_text = "no business-resource scope"
        else:
            scope_text = ", ".join(f"`{name}`" for name in row.required_oauth_scopes)
        lines.append(f"- Scopes: {scope_text}")
        if row.effect_kind:
            lines.append(f"- External effect: `{row.effect_kind}`")
        lines.append("")
    return lines


def inventory_page() -> str:
    return (
        "\n".join(
            [
                "# Generated by tests/reference/build_ui_pages.py from runtime/catalog.py.",
                "# Do not edit by hand.",
                "page_id: inventory-api",
                "title: Inventory API",
                "description: Every Shopify operation this extension can run, and what each one needs.",
                "project_scoped: false",
                "components:",
                "  - component_id: inventory_api_operations",
                "    type: markdown",
                "    title: Operations",
                "    body: |",
                _block(_operation_lines()),
            ]
        )
        + "\n"
    )


#: The record table each operation returns, for the coverage page.
_RESULT_RECORDS: dict[str, tuple[str, ...]] = {
    "get_shop": ("Shop",),
    "list_locations": ("Location",),
    "list_inventory_items": ("InventoryItem",),
    "get_inventory_item": ("InventoryItem",),
    "set_inventory_quantities": ("InventoryAdjustmentGroup",),
    "list_products": ("Product",),
    "export_products": ("Product", "ProductVariant"),
    "get_product": ("Product",),
    "create_product": ("Product", "ProductVariant"),
    "update_product": ("Product",),
    "list_product_variants": ("ProductVariant",),
    "get_product_variant": ("ProductVariant",),
    "create_product_variants_batch": ("ProductVariant",),
    "update_product_variants_batch": ("ProductVariant",),
    "list_catalog_metafields": ("Metafield",),
    "set_catalog_metafields": ("Metafield",),
    "list_product_media": ("Media",),
    "update_product_media": ("File",),
    "list_orders": ("Order",),
    "get_order": ("Order",),
    "update_order_metadata": ("Order",),
    "list_order_line_items": ("LineItem",),
    "list_order_metafields": ("Metafield",),
    "set_order_metafields": ("Metafield",),
    "list_order_fulfillment_orders": ("FulfillmentOrder",),
    "get_fulfillment_order": ("FulfillmentOrder",),
    "list_order_fulfillments": ("Fulfillment",),
    "create_fulfillment": ("Fulfillment",),
    "update_fulfillment_tracking": ("Fulfillment",),
}


def _eligible(snapshot: dict, type_name: str) -> list[str]:
    found = []
    for name, declared in snapshot["objects"][type_name].items():
        if declared["deprecated"] or any(a.endswith("!") for a in declared["args"].values()):
            continue
        target = named_type(declared["type"])
        if snapshot["kinds"].get(target) in ("SCALAR", "ENUM") or target in ("MoneyBag", "MoneyV2"):
            found.append(name)
    return found


def _coverage_lines() -> list[str]:
    snapshot = admin_schema.load()
    lines = [
        f"Every operation is checked, field by field, against Shopify's official Admin GraphQL "
        f"`{API_VERSION}` schema by the extension's own tests. The rule is complete coverage of "
        "each endpoint used:",
        "",
        "- **Writes:** every field of every Shopify input object the mutation accepts can be set.",
        "- **Lists:** every filter, sort and order argument Shopify offers can be used.",
        "- **Records:** every scalar and money field of the Shopify type is returned.",
        "",
        "Anything outside that rule is listed below with its reason. Pages are always read "
        "forwards (`first` and `after`; Shopify's `last` and `before` are not offered). "
        + coverage.MONEY_NOTE
        + " Related records — a customer, an address, a transaction — are not part of a record; "
        "where Flow Steward offers a dedicated operation for one, use that.",
        "",
    ]
    for row in OPERATIONS:
        if not row.document:
            continue
        operation = parse(row.document)
        lines.append(f"### {row.display_name} (`{row.operation_id}`)")
        lines.append("")
        if row.operation_id == "create_products_bulk":
            from runtime.bulk_documents import CREATE_ROW

            operation = parse(CREATE_ROW)
            lines.append("Shopify: `bulkOperationRunMutation`, running `productSet` for each row.")
        else:
            lines.append(f"Shopify: `{operation.selections[0].name}`.")
        root_field = operation.selections[0].name
        root_type = snapshot["roots"][operation.kind]
        if operation.kind == "mutation":
            paths = []
            for argument, type_ref in snapshot["objects"][root_type][root_field]["args"].items():
                paths.append(argument)
                target = named_type(type_ref)
                if snapshot["kinds"].get(target) == "INPUT_OBJECT":
                    paths += [f"{argument}.{p}" for p in admin_schema.input_paths(snapshot, target)]
            excluded = coverage.INPUT_EXCLUSIONS.get(row.operation_id, {})
            available = [
                path
                for path in paths
                if not any(path == item or path.startswith(f"{item}.") for item in excluded)
            ]
            lines.append(
                f"Inputs: {len(available)} of {len(paths)} official input fields can be set"
                + (", not offered:" if excluded else " — all of them.")
            )
            for path, reason in excluded.items():
                lines.append(f"- `{path}` — {reason}")
        for table in _RESULT_RECORDS.get(row.operation_id, ()):
            eligible = _eligible(snapshot, table)
            excluded_fields = coverage.FIELD_EXCLUSIONS.get(table, {})
            lines.append(
                f"Result `{table}`: {len(eligible) - len(excluded_fields)} of {len(eligible)} "
                "scalar and money fields" + (", without:" if excluded_fields else " — all of them.")
            )
            for name, reason in excluded_fields.items():
                lines.append(f"- `{name}` — {reason}")
        lines.append("")
    lines.append("### Arguments set by the extension itself")
    lines.append("")
    for field, arguments in coverage.ARGUMENT_EXCLUSIONS.items():
        for argument, reason in arguments.items():
            lines.append(f"- `{field}({argument})` — {reason}")
    return lines


def coverage_page() -> str:
    return (
        "\n".join(
            [
                "# Generated by tests/reference/build_ui_pages.py from runtime/coverage.py and",
                "# the pinned official schema slice. Do not edit by hand.",
                "page_id: api-coverage",
                "title: Shopify API coverage",
                "description: What of Shopify's official API each operation covers, and what it "
                "deliberately does not.",
                "project_scoped: false",
                "components:",
                "  - component_id: api_coverage",
                "    type: markdown",
                "    title: Coverage of the official Admin API",
                "    body: |",
                _block(_coverage_lines()),
            ]
        )
        + "\n"
    )


def changelog_page() -> str:
    """The Changelog page renders CHANGELOG.md, so the two cannot disagree."""
    body = CHANGELOG.read_text(encoding="utf-8").strip()
    lines = body.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
    return (
        "\n".join(
            [
                "# Generated by tests/reference/build_ui_pages.py from CHANGELOG.md.",
                "# Do not edit by hand.",
                "page_id: changelog",
                "title: Changelog",
                "description: What changed in each release of this extension.",
                "project_scoped: false",
                "components:",
                "  - component_id: changelog_entries",
                "    type: markdown",
                "    title: Release history",
                "    body: |",
                _block(lines),
            ]
        )
        + "\n"
    )


GENERATED_PAGES: dict[Path, object] = {
    INVENTORY_PAGE: inventory_page,
    COVERAGE_PAGE: coverage_page,
    CHANGELOG_PAGE: changelog_page,
}


def main() -> int:
    for path, render in GENERATED_PAGES.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render(), encoding="utf-8")  # type: ignore[operator]
        print(f"wrote {path.relative_to(BUNDLE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "CHANGELOG_PAGE",
    "COVERAGE_PAGE",
    "GENERATED_PAGES",
    "INVENTORY_PAGE",
    "changelog_page",
    "coverage_page",
    "inventory_page",
]
